export const LOGIN_AUTH = "LOGIN_AUTH";
export const LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS";
export const LOGIN_AUTH_FAILURE = "LOGIN_AUTH_FAILURE";
export const LOGOUT = "LOGOUT";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE ";
